# **「PyTorch入門 1. テンソル」**

In [ ]:
%matplotlib inline
import torch
import numpy as np
import matplotlib.pyplot as plt

# **データから直接テンソル(张量)に変換**


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

# **NumPy arrayからテンソル(张量)に変換**

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

# **他のテンソル(张量)から作成**

* 除非明确复写，否则会保留原有属性(张量的形状,数据的类型)




In [ ]:
x_ones = torch.ones_like(x_data) # x_dataの特性（プロパティ）を維持
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_dataのdatatypeを上書き更新
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6318, 0.0180],
        [0.1438, 0.1127]]) 



# **ランダム値や定数のテンソルの作成(随机数或常数张量的声明)**

In [ ]:
# shape是关于tensor维度的一个元组，在下面的函数中，它决定了输出tensor的维数
# shapeは、テンソルの次元を示すタプルです。
# 以下の例では、shapeからテンソルのサイズを決めています。

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7960, 0.6669, 0.5070],
        [0.5317, 0.3322, 0.4706]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# **テンソルの属性変数**

In [ ]:
# Tensor的属性包括形状，数据类型以及存储的设备
tensor = torch.rand(3,4)

# 形状
print(f"Shape of tensor: {tensor.shape}")
# データの型
print(f"Datatype of tensor: {tensor.dtype}")
# 保存されているデバイス
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# **テンソルの操作**
* 算術、線形代数、行列操作（転置、インデックス、スライス）など
* 各操作はGPU上で実行可能です（一般的にCPUの場合より高速です）

In [ ]:
# GPUが使用可能であれば、GPU上にテンソルを移動させる
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

# **numpy-likeなindexingとslicing:**

In [ ]:
tensor = torch.ones(4, 4)

# 第一行目
print('First row: ',tensor[0])

# 第一列目
print('First column: ', tensor[:, 0])

# 最後の列目
print('Last column:', tensor[..., -1])

# 毎行の第二列目を0にする
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# **テンソルの結合**

In [ ]:
# 可以使用torch.cat来沿着特定维数连接一系列张量
# torch.stack另一个加入op的张量与torch.cat有细微的不同
t1 = torch.cat([tensor, tensor, tensor], dim=1)  # 横着拼
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)  # 竖着拼
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# **算術演算**

In [ ]:
# 2つのテンソル行列のかけ算です。 y1, y2, y3 は同じ結果になります。
# 张量可以像矩阵一样进行运算
y1 = tensor @ tensor.T

# .T 张量的转置
print("tensor： ",tensor)
print("tensor.T： ",tensor.T)

# @ 张量的乘法
print("tensor @ tensor.T: ",y1)

y2 = tensor.matmul(tensor.T)
print("tensor.matmul: ",y2)

y3 = torch.rand_like(tensor)
print("torch.rand_like: ",y3)
torch.matmul(tensor, tensor.T, out=y3)
print("torch.matmul: ",y3)


tensor：  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.T：  tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor @ tensor.T:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor.matmul:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
torch.rand_like:  tensor([[0.2760, 0.3139, 0.8869, 0.4698],
        [0.8419, 0.8851, 0.1173, 0.1661],
        [0.5126, 0.3226, 0.5115, 0.9527],
        [0.7072, 0.8807, 0.9056, 0.0360]])
torch.matmul:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
# こちらは、要素ごとの積を求めます。 z1, z2, z3 は同じ値になります。
# 张量内对应元素的积
z1 = tensor * tensor
print("tensor * tensor: ",z1)
z2 = tensor.mul(tensor)
print("tensor.mul: ",z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print("torch.mul: ",z3)

tensor * tensor:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.mul:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.mul:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# **1要素のテンソル**(一个元素的张量)

In [ ]:
# 张量内各个元素之和
agg = tensor.sum()
print(agg)

# 获取张量内的元素
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


# **インプレース操作**(原地操作)

In [ ]:
# 带有后缀``_``的操作表示的是原地操作，例如： ``x.copy_(y)``, ``x.t_()``将改变 ``x``
print(tensor, "\n")

# 张量的每个元素都 +5
tensor.add_(5)
print(tensor)

# 注意：原地操作虽然会节省许多空间，但是由于会立刻清除历史记录所以在计算导数时可能会有问题，因此不建议使用


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# **NumPyとの変換**
* Tensor to NumPy array

In [ ]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")
t.add_(1)

# tensor的变化反映在NumPy数组中
print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


* NumPy array to Tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

np.add(n, 1, out=n)

# NumPy数组的变化反映在tensor中
print(f"t: {t}")
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
